### ISSUE TITLE
`deriveOrd1` reflexivity bug

### ISSUE THREAD

**Issue by LightAndLight** [haskell-compat/deriving-compat#31]
There are a certain class of datatypes for which `deriveOrd1` derives incorrect instances. I'm using GHC8.6.5 and deriving-compat-0.5.8.

Here's a minimal example:

```
{-# language TemplateHaskell #-}
module Main where

import Data.Deriving (deriveEq1, deriveOrd1)
import Data.Functor.Classes (compare1, eq1)
import Data.Void (Void)

data T a
  = A
  | B Int
  | C Int
  | D
  | E Int
  | F
deriveEq1 ''T
deriveOrd1 ''T
instance Eq a => Eq (T a) where; (==) = eq1
instance Ord a => Ord (T a) where; compare = compare1

main :: IO ()
main =
  let
    x = E 0 :: T Void
  in
    print $ compare x x
```

Running this program prints `LT`.

I hacked up a hedgehog generator to investigate (https://github.com/LightAndLight/deriveOrd1-bug), and the above example was arrived at after a generous amount of testing and shrinking. It appears 6 constructors is the minimum required to see the issue, but the problem can surface for more constructors.

7 constructor example:
```
data T a
  = A Int
  | B
  | C
  | D Int
  | E Int
  | F
  | G

...

let x = E 0 :: T Void
```

8 constructor example:
```
data T a
  = A
  | B
  | C Int
  | D
  | E Int
  | F Int
  | G
  | H

...

let x = F 0 :: T Void
```

You can tweak the parameters in the hedgehog test to find counterexamples of varying sizes.

The problem can only be seen for certain constructors. In the 6 constructor example, only `E` is affected.

**Comment by RyanGlScott** [comment]
Good catch! I've submitted #32 with a fix.

**Comment by RyanGlScott** [comment]
I've uploaded [deriving-compat-0.5.9](http://hackage.haskell.org/package/deriving-compat-0.5.9) to Hackage with a fix.

**Comment by LightAndLight** [comment]
Wonderful. Thanks Ryan :)
