### ISSUE TITLE
Please, upd docs to lean less heavy on that it is only a backporting package

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-compat/deriving-compat#35]
For `hnix`, `deriving-compat` for years allows to derive instances that GHC can not:

https://github.com/haskell-nix/hnix/issues/321, especially: https://github.com/haskell-nix/hnix/issues/321#issuecomment-392734182.

People are wondering why such superb functionality is hidden in the backward-compatibility package.

Since package name can not be changed easily - the path of least effort is to make introduction docs say that it is not only for backward compatibility, but TH deriving allows sometimes to derive instances that GHC can not derive.

Thank you for reading.

**Comment by RyanGlScott** [comment]
Yes, a fair point. I originally put things like `deriveEq1` in `deriving-compat` as I had ambitions to try and make GHC able to derive instances of `Eq1`, but those ambitions never materialized. That does make the inclusion of `deriveEq1` _et al._ in `deriving-compat` a bit suspect, but it's just too darn useful to remove at this point.

I've opened #35, which attempts to improve the documentation regarding this subject. Are things clearer with the prose in #35?

**Comment by RyanGlScott** [comment]
Fixed in #36. Let me know if you'd like to have a new Hackage release soon. Otherwise, I'll wait until there are other changes before making a new release.
